default_agent: cost_analysis_agentcore
agents:
  well_architected_security_agentcore:
    name: well_architected_security_agentcore
    entrypoint: /persistent/home/ubuntu/workspace/agenticaihackathon/well_architected_security_agentcore.py
    platform: linux/arm64
    container_runtime: docker
    source_path: /persistent/home/ubuntu/workspace/agenticaihackathon
    aws:
      execution_role: arn:aws:iam::039920874011:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-a29f784568
      execution_role_auto_create: false
      account: 039920874011
      region: us-east-1
      ecr_repository: 039920874011.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-well_architected_security_agentcore
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: well_architected_security_agentcore-uBgBoaAnRs
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:039920874011:runtime/well_architected_security_agentcore-uBgBoaAnRs
      agent_session_id: c18a1510-a292-4755-9e61-3d85ac874399
    codebuild:
      project_name: bedrock-agentcore-well_architected_security_agentcore-builder
      execution_role: arn:aws:iam::039920874011:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-a29f784568
      source_bucket: bedrock-agentcore-codebuild-sources-039920874011-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: well_architected_security_agentcore_mem-mmKAPcGPsE
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:039920874011:memory/well_architected_security_agentcore_mem-mmKAPcGPsE
      memory_name: well_architected_security_agentcore_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
  cost_analysis_agentcore:
    name: cost_analysis_agentcore
    entrypoint: /persistent/home/ubuntu/workspace/agenticaihackathon/cost_analysis_agentcore.py
    platform: linux/arm64
    container_runtime: docker
    source_path: /persistent/home/ubuntu/workspace/agenticaihackathon
    aws:
      execution_role: arn:aws:iam::039920874011:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-9dcf2ab8b0
      execution_role_auto_create: false
      account: 039920874011
      region: us-east-1
      ecr_repository: 039920874011.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-cost_analysis_agentcore
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: cost_analysis_agentcore-UTdyrMH0Jo
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:039920874011:runtime/cost_analysis_agentcore-UTdyrMH0Jo
      agent_session_id: 8e0e38a8-933a-4a52-8fb6-61bb291e6c6f
    codebuild:
      project_name: bedrock-agentcore-cost_analysis_agentcore-builder
      execution_role: arn:aws:iam::039920874011:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-9dcf2ab8b0
      source_bucket: bedrock-agentcore-codebuild-sources-039920874011-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: cost_analysis_agentcore_mem-BaiiB5B1gC
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:039920874011:memory/cost_analysis_agentcore_mem-BaiiB5B1gC
      memory_name: cost_analysis_agentcore_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
