name: security-roi-calculator
description: Security ROI Calculator with AgentCore Memory Primitive
version: 1.0.0

runtimes:
  - name: well-architected-security
    file: well_architected_security_agentcore.py
    description: Security posture analysis and findings
    memory_integration: true
    
  - name: cost-analysis
    file: cost_analysis_agentcore.py
    description: Security cost analysis and ROI calculation
    memory_integration: true

environment:
  region: us-west-2
  memory_enabled: true
  
dependencies:
  - bedrock-agentcore
  - boto3

tools:
  security:
    - analyze_security_posture
    - get_security_findings
  cost:
    - get_security_costs
    - calculate_security_roi
    - get_roi_trends
